# -------------------------------
# APP INFO
# -------------------------------
spring.profiles.active=prod
spring.application.name=ZaloCloneBe

server.address=0.0.0.0
server.port=${PORT:8080}
server.tomcat.connection-timeout=20000
spring.main.lazy-initialization=false


# -------------------------------
# DATABASE CONFIG (POSTGRES - NEON)
# -------------------------------
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# -------------------------------
# JPA / HIBERNATE
# -------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# -------------------------------
# WEBSOCKET
# -------------------------------
spring.websocket.enabled=true


# -------------------------------
# SECURITY / OTHER
# -------------------------------
recaptcha.secret=${RECAPTCHA_SECRET}
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
login.max-fail=3


# -------------------------------
# FILE UPLOAD
# -------------------------------
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
