# ===============================
# PROD (RENDER)
# ===============================

spring.profiles.active=prod

server.address=0.0.0.0
server.port=${PORT:8080}

# -------------------------------
# POSTGRES (NEON)
# -------------------------------
spring.datasource.url=jdbc:postgresql://ep-wandering-wildflower-a1tt72tv-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_G2A9EuNXRWIT
spring.datasource.driver-class-name=org.postgresql.Driver

# -------------------------------
# JPA
# -------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
